"use client";

import { useState } from "react";
import dynamic from "next/dynamic";
import Link from "next/link";
import { ChevronRight } from "lucide-react";

const GradientWaves = dynamic(() => import("~~/components/encrypool/gradient-waves"), { ssr: false });

type FaqItem = { q: string; a: string };
type FaqSection = { title: string; emoji?: string; items: FaqItem[] };

const sections: FaqSection[] = [
  {
    title: "General",
    items: [
      {
        q: "Where does the prize money come from?",
        a: "Prize money comes directly from the interest generated by the pooled deposits. When participants deposit cUSDT into the prize pool, the assets are held in a smart contract that accrues yield. Rather than distributing yield equally, Encrypool uses a encrypted draw mechanism to award the full accrued amount to one randomly selected winner each round — a no-loss model where everyone keeps their principal.",
      },
      {
        q: "Do I have to enter for each prize?",
        a: "No. Once you deposit into the prize pool, your deposit automatically qualifies you for every future draw. There is no need to re-enter or submit additional transactions. Your encrypted balance is carried forward each round until you decide to withdraw.",
      },
      {
        q: "Is there any penalty to withdraw?",
        a: "No. There is zero penalty for withdrawing at any time. Your principal is fully intact — Encrypool is a no-loss protocol. You can withdraw your full cUSDT deposit whenever you choose without losing eligibility for the current round, as long as you withdraw before the draw snapshot is taken.",
      },
      {
        q: "How are winners chosen? How is it fair?",
        a: "Winners are chosen through a verifiable on-chain draw process. A randomness request is submitted to the FHEVM co-processor which generates encrypted entropy. Once fulfilled, the encrypted winner index is revealed on-chain. The draw is weighted by deposit amount and time held — larger or longer-held deposits receive proportionally higher odds. All draw data is encrypted until reveal, preventing front-running or manipulation.",
      },
      {
        q: "Is there an advantage to depositing early?",
        a: "Yes. The draw weight system rewards early depositors. Your weight grows with the time your funds remain in the pool between draws. Depositing earlier in a draw cycle gives your balance more time to accumulate weight, slightly increasing your odds compared to depositing at the last moment. However, the difference is modest — all depositors always have a meaningful chance of winning.",
      },
      {
        q: "Which Prize Pool should I choose?",
        a: "Encrypool is designed to support multiple prize pools in the future. Currently on Sepolia testnet, there is one active cUSDT pool. When multiple pools launch, your choice depends on your preferred token, desired prize frequency, and risk tolerance. Each pool operates independently with its own encrypted draw cycle.",
      },
      {
        q: "Can I lose my money? What are the risks?",
        a: "Encrypool follows a no-loss model — your deposited principal is always fully withdrawable. The primary smart contract risk is standard for DeFi protocols: potential vulnerabilities in the contract code, the FHEVM co-processor, or the underlying cUSDT token. All contracts have been audited and the protocol is open-source. There is no impermanent loss or liquidation risk.",
      },
      {
        q: "Are my deposits insured?",
        a: "No. Like most DeFi protocols, Encrypool deposits are not insured. However, the no-loss model inherently protects your principal — you are not using leverage or lending your funds to third parties. The contract holds your cUSDT directly and you can withdraw it at any time.",
      },
    ],
  },
  {
    title: "Prizes & Winning",
    emoji: "🏆",
    items: [
      {
        q: "What are my odds to win?",
        a: "Your odds are proportional to your encrypted deposit weight. Weight is calculated from your deposit amount multiplied by the time you have held it in the pool. A larger or longer-held deposit means higher odds — but every depositor always has a non-zero chance. The exact odds are not visible to anyone until the encrypted draw is revealed.",
      },
      {
        q: "How many prizes are awarded?",
        a: "One prize is awarded per draw cycle. Each draw selects a single winner who receives the entire accrued prize pool for that round. The prize amount depends on the total deposits and the yield generated during the draw interval.",
      },
      {
        q: "How do I get my prizes?",
        a: "When you win a draw, your prize is automatically credited to your account in the pool contract. Navigate to the Account page and you will see a claimable prize card. Click the claim button to receive your cUSDT prize directly to your wallet. You must claim before the next draw — unclaimed prizes roll back into the pool.",
      },
      {
        q: "What does the Daily Prize Value mean?",
        a: "The Daily Prize Value represents the estimated yield generated by the total pool deposits per day. It is calculated based on the current APY of the underlying yield source. This value determines how large the prize payout will be when the next draw occurs. Higher TVL and higher yield rates increase the daily prize value.",
      },
      {
        q: "What prevents someone from joining at the last second?",
        a: "The time-weighted draw system disincentivizes last-second deposits. While anyone can deposit at any time before a draw, late depositors receive minimal time-based weight. This means a user who deposited days ago has meaningfully higher odds than someone who deposited minutes before the snapshot. The encrypted nature of balances also prevents front-running — nobody can see the current weights to game the system.",
      },
      {
        q: "What is the Prize Cap?",
        a: "The Prize Cap is a maximum limit on the prize payout per draw. It prevents any single draw from awarding an excessively large amount, ensuring sustainable prize distribution. If accrued yield exceeds the cap, the excess stays in the pool for future draws. The cap can be adjusted by the protocol governance.",
      },
      {
        q: 'What is the "Prize APR"?',
        a: "The Prize APR is the effective annualized return you can expect from winning prizes, calculated as (total annual prize value / your deposit) × 100%. It differs from the raw yield APY because prizes are distributed to one winner rather than split evenly. Your actual expected return depends on your odds of winning, which are proportional to your weight in the pool.",
      },
      {
        q: "How long do I have to claim my prizes?",
        a: "You have until the next draw is fulfilled to claim your prize. If you do not claim before the subsequent draw occurs, the unclaimed amount is recycled back into the prize pool for future rounds. We recommend checking your Account page regularly after each draw to claim any winnings promptly.",
      },
      {
        q: "Can I see who won?",
        a: "Yes. The Prizes page displays all historical draws with the winning wallet address, prize amount, and claim status. While deposit amounts and balances are encrypted (using FHE), the winner identity and payout amount are public once the draw is fulfilled — ensuring transparency while preserving privacy of all other participants' balances.",
      },
    ],
  },
];

function FaqCard({ item }: { item: FaqItem }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="rounded-2xl border border-border/60 bg-card/60 backdrop-blur-xl transition-colors hover:border-border">
      <button
        onClick={() => setOpen(!open)}
        className="flex w-full items-center gap-3 px-6 py-5 text-left"
        aria-expanded={open}
      >
        <ChevronRight
          className={`shrink-0 size-5 text-muted-foreground transition-transform duration-200 ${open ? "rotate-90" : ""}`}
        />
        <span className="text-base font-medium text-foreground">{item.q}</span>
      </button>
      {open && (
        <div className="px-6 pb-5 pl-14">
          <p className="text-sm leading-relaxed text-muted-foreground">{item.a}</p>
        </div>
      )}
    </div>
  );
}

export default function InfoPage() {
  return (
    <main className="relative min-h-[calc(100svh-192px)]">
      <div className="absolute inset-0 z-0">
        <GradientWaves
          horizonColor="#0a0e1a"
          waveColor="#2a1060"
          crestColor="#ff6b4a"
          speed={0.25}
          amplitude={1.8}
          waveScale={0.5}
          waveRatio={1.4}
          swell={28}
          turbulence={15}
          tilt={1.05}
          zoom={0.9}
          height={4.5}
          fogDepth={22}
          detail="medium"
          brightness={0.7}
          opacity={0.65}
          mouseInteraction
          parallaxStrength={0.3}
          grain
          grainIntensity={0.04}
        />
        <div className="absolute inset-0 bg-gradient-to-b from-background/40 via-background/70 to-background/95" />
      </div>

      <div className="relative z-10 mx-auto max-w-4xl px-5 py-20 lg:px-8">
        <div className="mb-14 text-center">
          <h1 className="font-serif text-4xl font-bold tracking-tight sm:text-5xl">Learn about Encrypool</h1>
          <p className="mt-4 text-lg text-muted-foreground">
            Everything you need to know about the no-loss encrypted prize savings protocol.
          </p>
        </div>

        <div className="space-y-16">
          {sections.map(section => (
            <section key={section.title} id={section.title.toLowerCase().replace(/\s+/g, "-")}>
              <h2 className="mb-6 flex items-center gap-3 text-2xl font-bold tracking-tight">
                <span className="text-primary">#</span>
                {section.title} {section.emoji && <span>{section.emoji}</span>}
              </h2>
              <div className="space-y-3">
                {section.items.map(item => (
                  <FaqCard key={item.q} item={item} />
                ))}
              </div>
            </section>
          ))}
        </div>

        <div className="mt-16 text-center">
          <Link
            href="/vaults"
            className="inline-flex items-center gap-2 rounded-full bg-primary px-8 py-3 font-semibold text-primary-foreground shadow-[0_0_24px_color-mix(in_srgb,var(--primary)_30%,transparent)] transition-all hover:shadow-[0_0_36px_color-mix(in_srgb,var(--primary)_45%,transparent)]"
          >
            Start Saving
          </Link>
        </div>
      </div>
    </main>
  );
}
