/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./ConfidentialPrizePool.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { ConfidentialPrizePool } from "~~/contracts/ConfidentialPrizePool";`
 */
import { ConfidentialPrizePool as ConfidentialPrizePool_LOCAL } from "./ConfidentialPrizePool.local";
import type { ContractDeployment } from "~~/utils/contract";

const REMOTE = {
  11155111: {
    address: "0x0ec801753010A720E6Bae8069d33be2f3C52879a",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "asset_",
            type: "address",
            internalType: "contract IERC7984",
          },
          {
            name: "vault_",
            type: "address",
            internalType: "contract ConfidentialPrizeVault",
          },
          {
            name: "tracker_",
            type: "address",
            internalType: "contract EncryptedBalanceTracker",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "MIN_DRAW_INTERVAL",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint64",
            internalType: "uint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "asset",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "contract IERC7984",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "claim",
        inputs: [
          {
            name: "drawId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "draw",
        inputs: [],
        outputs: [
          {
            name: "drawId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "fulfillWinner",
        inputs: [
          {
            name: "drawId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "winnerIndex",
            type: "uint8",
            internalType: "uint8",
          },
          {
            name: "decryptionProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "fundPrize",
        inputs: [
          {
            name: "encryptedAmount",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "getDraw",
        inputs: [
          {
            name: "drawId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "tuple",
            internalType: "struct ConfidentialPrizePool.Draw",
            components: [
              {
                name: "seedIndex",
                type: "bytes32",
                internalType: "euint8",
              },
              {
                name: "amount",
                type: "bytes32",
                internalType: "euint64",
              },
              {
                name: "winner",
                type: "address",
                internalType: "address",
              },
              {
                name: "fulfilled",
                type: "bool",
                internalType: "bool",
              },
              {
                name: "claimed",
                type: "bool",
                internalType: "bool",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "participantCount",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "participants",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address[]",
            internalType: "address[]",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "prizeLiquidity",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "registerParticipant",
        inputs: [
          {
            name: "account",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "seedIndexOf",
        inputs: [
          {
            name: "drawId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "vault",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "contract ConfidentialPrizeVault",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "weightSource",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "contract EncryptedBalanceTracker",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "event",
        name: "ParticipantRegistered",
        inputs: [
          {
            name: "account",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "PrizeClaimed",
        inputs: [
          {
            name: "drawId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "winner",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "PrizeFunded",
        inputs: [
          {
            name: "amount",
            type: "bytes32",
            indexed: false,
            internalType: "euint64",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "PublicDecryptionVerified",
        inputs: [
          {
            name: "handlesList",
            type: "bytes32[]",
            indexed: false,
            internalType: "bytes32[]",
          },
          {
            name: "abiEncodedCleartexts",
            type: "bytes",
            indexed: false,
            internalType: "bytes",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "WinnerSeeded",
        inputs: [
          {
            name: "drawId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "seedIndex",
            type: "bytes32",
            indexed: false,
            internalType: "euint8",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "WinnerSet",
        inputs: [
          {
            name: "drawId",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "winner",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "DrawAlreadyClaimed",
        inputs: [],
      },
      {
        type: "error",
        name: "DrawAlreadyFulfilled",
        inputs: [],
      },
      {
        type: "error",
        name: "DrawNotFulfilled",
        inputs: [],
      },
      {
        type: "error",
        name: "DrawTooSoon",
        inputs: [],
      },
      {
        type: "error",
        name: "InvalidKMSSignatures",
        inputs: [],
      },
      {
        type: "error",
        name: "InvalidWinnerIndex",
        inputs: [],
      },
      {
        type: "error",
        name: "NoParticipants",
        inputs: [],
      },
      {
        type: "error",
        name: "NotWinner",
        inputs: [],
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "TooManyParticipants",
        inputs: [],
      },
      {
        type: "error",
        name: "UnauthorizedCaller",
        inputs: [
          {
            name: "caller",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 11628702,
  },
} as const;

export const ConfidentialPrizePool = {
  ...REMOTE,
  ...ConfidentialPrizePool_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
