/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./ConfidentialPrizeVault.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { ConfidentialPrizeVault } from "~~/contracts/ConfidentialPrizeVault";`
 */
import { ConfidentialPrizeVault as ConfidentialPrizeVault_LOCAL } from "./ConfidentialPrizeVault.local";
import type { ContractDeployment } from "~~/utils/contract";

const REMOTE = {
  11155111: {
    address: "0x657c784067C0761a32eA399d12132f30Ebf5C714",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "asset_",
            type: "address",
            internalType: "contract IERC7984",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "asset",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "contract IERC7984",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "balanceTracker",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "contract EncryptedBalanceTracker",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "deposit",
        inputs: [
          {
            name: "encryptedAmount",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "positionOf",
        inputs: [
          {
            name: "account",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "prizePool",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "contract IParticipantRegistry",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "setPrizePool",
        inputs: [
          {
            name: "pool",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "totalAssets",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalShares",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "bytes32",
            internalType: "euint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "withdraw",
        inputs: [
          {
            name: "encryptedAmount",
            type: "bytes32",
            internalType: "externalEuint64",
          },
          {
            name: "inputProof",
            type: "bytes",
            internalType: "bytes",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Deposited",
        inputs: [
          {
            name: "account",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "shares",
            type: "bytes32",
            indexed: false,
            internalType: "euint64",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "PrizePoolSet",
        inputs: [
          {
            name: "prizePool",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "Withdrawn",
        inputs: [
          {
            name: "account",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "shares",
            type: "bytes32",
            indexed: false,
            internalType: "euint64",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "PrizePoolAlreadySet",
        inputs: [],
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 11628702,
  },
} as const;

export const ConfidentialPrizeVault = {
  ...REMOTE,
  ...ConfidentialPrizeVault_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
